//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class child_portfolio
    {
        public int child_portfolio_id { get; set; }
        public int child_id { get; set; }
        public string child_private_health_data { get; set; }
        public string child_private_mental_health_data { get; set; }
        public string child_achivements { get; set; }
    
        public virtual child child { get; set; }
    }
}
