//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mother
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mother()
        {
            this.child = new HashSet<child>();
        }
    
        public int mother_id { get; set; }
        public string mother_surname { get; set; }
        public string mother_name { get; set; }
        public string mother_patronymic { get; set; }
        public string mother_passport_data { get; set; }
        public System.DateTime mother_Bday { get; set; }
        public string mother_phone { get; set; }
        public string mother_education { get; set; }
        public string mother_job { get; set; }
        public string mother_login { get; set; }
        public string mother_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<child> child { get; set; }
    }
}
