//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psychologist
    {
        public int psychologist_id { get; set; }
        public int organization_id { get; set; }
        public string psychologist_surname { get; set; }
        public string psychologist_name { get; set; }
        public string psychologist_patronymic { get; set; }
        public string psychologist_education { get; set; }
        public string psychologist_category { get; set; }
        public int psychologist_experience { get; set; }
        public int psychologist_cabinet { get; set; }
        public string psychologist_phone { get; set; }
        public string psychologist_login { get; set; }
        public string psychologist_passport_data { get; set; }
    
        public virtual organization organization { get; set; }
    }
}
