//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int report_id { get; set; }
        public int author_id { get; set; }
        public int auditor_id { get; set; }
        public string text { get; set; }
        public string saved { get; set; }
        public string sended { get; set; }
    
        public virtual methodist methodist { get; set; }
        public virtual superintendent superintendent { get; set; }
    }
}
