//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int schedule_id { get; set; }
        public int schedule_group_id { get; set; }
        public string beginning { get; set; }
        public string breakfast { get; set; }
        public string morninggames { get; set; }
        public string walking { get; set; }
        public string lunch { get; set; }
        public string sleep { get; set; }
        public string eveninggames { get; set; }
        public string dinner { get; set; }
        public string eveningwalking { get; set; }
        public string ending { get; set; }
    
        public virtual group group { get; set; }
    }
}
